name: Build Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install check
     # or check-dev (?)

    - name: Build with Make & launch tests
      run: |
        working-directory: ${{github.workspace}}/docker
        chmod +x test_s21_decimal.sh
        ./test_s21_decimal.sh
        
  build_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build with Make & launch tests
      run: |
        working-directory: ${{github.workspace}}/docker
        chmod +x test_s21_decimal.sh
        ./test_s21_decimal.sh
    
  build_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker container & run it
      run: |
        working-directory: ${{github.workspace}}/docker
        chmod +x run_daemon.sh
        ./run_daemon.sh